# Generated by Django 3.0.5 on 2020-05-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200523_1452'),
        ('Moods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic_Moods',
            fields=[
                ('generic_mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Mood',
            fields=[
                ('patient_mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('logged_time', models.DateTimeField(blank=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('generic_mood', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Moods.Generic_Moods')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Patient_User')),
            ],
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
