# Generated by Django 3.0.5 on 2020-05-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200522_1853'),
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_proof',
            name='activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Activities.Activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='patient_activities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Patient_User'),
        ),
    ]
