# Generated by Django 3.0.5 on 2020-05-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_auto_20200523_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activity',
            new_name='id',
        ),
    ]
