# Generated by Django 3.0.5 on 2020-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20200527_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activity_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='activity_name',
            new_name='name',
        ),
    ]
