# Generated by Django 3.0.5 on 2020-05-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_auto_20200527_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_types',
            old_name='activity_type',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='assigned_activities',
            old_name='assigned_activities',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='completed_activities',
            old_name='completed_activities',
            new_name='assinged_activity',
        ),
        migrations.RenameField(
            model_name='proof_activities',
            old_name='proof',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='proof_activities_type',
            old_name='proof_type',
            new_name='id',
        ),
    ]
