# Generated by Django 3.0.5 on 2020-05-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_diagnosis_patient_user_psychologist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_user',
            name='psychologist_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Psychologist_User'),
        ),
        migrations.AlterField(
            model_name='user_roles',
            name='roleid',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Roles'),
        ),
        migrations.AlterField(
            model_name='user_roles',
            name='userid',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
        ),
    ]
