# Generated by Django 3.0.5 on 2020-05-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200522_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_user',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='psychologist_user',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='patient_user',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.User'),
        ),
        migrations.AddField(
            model_name='psychologist_user',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.User'),
        ),
    ]
