# Generated by Django 3.0.5 on 2020-05-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200523_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_user',
            old_name='psychologist_id',
            new_name='psychologist',
        ),
        migrations.RenameField(
            model_name='user_roles',
            old_name='roleid',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user_roles',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='patient_user',
            name='diagnosis_id',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient_user',
            name='diagnosis',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Diagnosis'),
        ),
        migrations.AddField(
            model_name='psychologist_user',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologist_user',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
