# Generated by Django 3.0.5 on 2020-05-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200523_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='user_id',
        ),
    ]
