# Generated by Django 3.0.5 on 2020-05-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200523_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tile',
            new_name='title',
        ),
    ]
