# Generated by Django 3.0.5 on 2020-05-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0008_auto_20200528_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255, null=True)),
                ('medication_description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructions', models.CharField(max_length=255, null=True)),
                ('dosage', models.IntegerField(default=1)),
                ('dosage_time_hours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Medication.List_Medication')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Patient_User')),
            ],
        ),
        migrations.CreateModel(
            name='Taken_Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_taken', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patients_medication', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Medication.Patient_Medication')),
            ],
        ),
    ]
